"""Add reset_token fields to user

Revision ID: 055db9e935b8
Revises: 53e771c3b30a
Create Date: 2025-07-29 11:32:12.623836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055db9e935b8'
down_revision = '53e771c3b30a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=256), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_column('job_type')
        batch_op.drop_column('company')
        batch_op.drop_column('salary')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')

    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('company', sa.VARCHAR(length=255), server_default=sa.text("'Unknown Company'::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('job_type', sa.VARCHAR(length=50), server_default=sa.text("'Full-time'::character varying"), autoincrement=False, nullable=False))

    op.drop_table('notifications')
    # ### end Alembic commands ###
