"""Convert user role to PostgreSQL ENUM

Revision ID: d4a741d492dd
Revises: 1d056e5f8182
Create Date: 2025-07-19 22:10:01.414974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4a741d492dd'
down_revision = '1d056e5f8182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ENUM type
    op.execute("CREATE TYPE user_role_enum AS ENUM ('job_seeker', 'employer', 'admin')")

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=postgresql.ENUM('job_seeker', 'employer', 'admin', name='user_role_enum'),
               existing_nullable=True,
               postgresql_using="role::user_role_enum")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('job_seeker', 'employer', 'admin', name='user_role_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # Drop the ENUM type
    op.execute("DROP TYPE user_role_enum")

    # ### end Alembic commands ###